### ISSUE TITLE
Event / GlobalEvents Priority Performance Issue

### ISSUE THREAD

**Issue by chuckbergeron** [ArchonInteractive/SwissArmyLib#2]
Allo,

Thanks for putting this together. I noticed large memory and performance issues using delegates & events so I decided to give the SwissArmyLib interface approach a shot. After implementing the latest stable release (1.0.56), I noticed a large CPU issue with the new event code. 

I used the Deep Profiler to figure out what the issue was and it pointed me towards the Equals comparer being called 750,000~ times. Here's a screenshot from the profiler:

![skytropolis--load-from-save-deep-profile3](https://user-images.githubusercontent.com/35717/31043041-d9e30c98-a569-11e7-97a1-4afe9b30d894.PNG)

After ripping out the priority code (which our game doesn't require) performance is as smooth as silk. 😄

**Comment by Phault** [comment]
Thanks for the detailed report. Phew that is pretty crazy performance, I'll take a look at this as soon as I get back to a decent computer.  

Happy to hear you worked around the issue :)

**Comment by Phault** [comment]
I just pushed an update that should help significantly with the performance. Could you please test it to see if it helps with your usecase?

**Comment by chuckbergeron** [comment]
Nice, I tried out the new release and it works. I didn't even have to update my code, so I'm assuming you made priorities optional? That's awesome.

Thanks for the quick reply!

**Comment by Phault** [comment]
Glad to hear. :smile: 

Nope, priorities are just as optional as before, but if you don't use them (everything has 0 priority) then there's should only be a minuscule overhead (a simple check to see if the last item in the list has the same priority). 

The problem was actually with DelayedList when removals hadn't been processed yet and new items were added which made it look through and remove from the list of removals. That was the cause of the extreme amount of comparisons. I fixed it by making DelayedList queue up actions instead of keeping multiple lists. I also did a bunch of other tweaks, including making the comparison of unity objects a bit cheaper. 

No problem. This was a pretty big issue since the entire point of the events was to be more performant than delegates. :smile:
